### ISSUE TITLE
VU-meter - compile error

### ISSUE THREAD

**Issue by netmindz** [K9260/Arduino#1]
When trying to build for D1 mini with Arduino 1.8.5 I get the following error. Looks like they should return void

In file included from /home/will/Arduino/K9620-VU-meter/VU-meter/VU-meter.ino:1:0:
/home/will/Arduino/libraries/FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.001
 #    pragma message "FastLED version 3.002.001"
                     ^
In file included from /home/will/Arduino/libraries/FastLED/FastLED.h:65:0,
                 from /home/will/Arduino/K9620-VU-meter/VU-meter/VU-meter.ino:1:
/home/will/Arduino/libraries/FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
VU-meter:44: error: ISO C++ forbids declaration of 'Move' with no type [-fpermissive]
   Move() {
        ^
VU-meter:63: error: ISO C++ forbids declaration of 'NewColor' with no type [-fpermissive]
   NewColor() {
            ^
VU-meter:67: error: ISO C++ forbids declaration of 'Init' with no type [-fpermissive]
   Init() {
        ^
VU-meter:94: error: ISO C++ forbids declaration of 'Move' with no type [-fpermissive]
   Move() {
        ^
VU-meter:109: error: ISO C++ forbids declaration of 'Init' with no type [-fpermissive]
   Init(float Fade, int MaxLife) {
                               ^
VU-meter:140: error: ISO C++ forbids declaration of 'Shine' with no type [-fpermissive]
   Shine() {
         ^
VU-meter:148: error: ISO C++ forbids declaration of 'Init' with no type [-fpermissive]
   Init() {
        ^
VU-meter:165: error: 'int index' redeclared as different kind of symbol
 int index = 0;
     ^
In file included from /home/will/.arduino15/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include/stdlib.h:11:0,
                 from /home/will/.arduino15/packages/esp8266/hardware/esp8266/2.4.2/cores/esp8266/Arduino.h:27,
                 from sketch/VU-meter.ino.cpp:1:
/home/will/.arduino15/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include/string.h:54:15: error: previous declaration of 'char* index(const char*, int)'
 char  *_EXFUN(index,(const char *, int));
               ^
/home/will/.arduino15/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include/_ansi.h:65:30: note: in definition of macro '_EXFUN'
 #define _EXFUN(name, proto)  name proto
                              ^
exit status 1
ISO C++ forbids declaration of 'Move' with no type [-fpermissive]

**Comment by K9260** [comment]
Interesting... if you can figure it out let me know.
I don't have this issue on my Arduino Uno

**Comment by Kodekat84** [comment]
Running into the same issues with the nested calls within bubble and ripple "VU-meter:44: error: ISO C++ forbids declaration of 'Move' with no type [-fpermissive]
Move() {"

trying to utilize this on a teensy.  I'll update moving forward- just wanted you to be aware.  Thanks!

**Comment by K9260** [comment]
> Running into the same issues with the nested calls within bubble and ripple "VU-meter:44: error: ISO C++ forbids declaration of 'Move' with no type [-fpermissive]
> Move() {"
> 
> trying to utilize this on a teensy. I'll update moving forward- just wanted you to be aware. Thanks!

I tried the code on my ESP-12 and I tumbled across the same problem. Quick google search shows it could be related to either the functions not returning anything or then there is problem with the way I have named these structs. I'll try to look into it on the weekend

**Comment by K9260** [comment]
Hey, maybe give a try and write "void" in front of all struct functions. It seems like I have completely forgotten to do that but oddly enough arduino compiler doesnt seem to care whether I write void or leave the function without it. I need to do more research on the issue

**Comment by K9260** [comment]
The solutuion seems to be adding void in front of all struct functions and renaming variable index. 
This should now work on your boards too, at least compiled perfectly to my ESP boards that had same issue before! 
I will mark the issue closed for now :)
